#!/bin/sh

$JAVA_HOME/bin/java \
   -jar target/oscar-runtime*.jar $*

#   --add-exports org.graalvm.truffle/com.oracle.truffle.api.nodes=ALL-UNNAMED \
#   --add-exports org.graalvm.truffle/com.oracle.truffle.api=ALL-UNNAMED \
#   --add-exports org.graalvm.truffle/com.oracle.truffle.api.dsl=ALL-UNNAMED \
